### ISSUE TITLE
Only text fields can be located by their label

### ISSUE THREAD

**Issue by jkotests** [watir/watir-classic#58]
It is only possible to locate text fields based on their label (ie other input fields cannot be located by their label).

Given the html:

````html
<input type="checkbox" name="new_user_interests" id="new_user_interests_books" value="books" checked="checked" />
<label for="new_user_interests_books">Books</label>
````

It is not possible to find the checkbox by its label (as it appears to be comparing a Watir::Label object):

````ruby
p browser.checkbox(:label, 'Books').exists?
#=> false
````

**Comment by ShettyA** [comment]
Any update on this issue?

**Comment by jkotests** [comment]
I plan to get this fixed in the near future. Please bare with us as we have had some team changes.

**Comment by ShettyA** [comment]
Thanks for the quick update. 
My watir test currently does detect the checkbox sometimes but is very unstable and fails 50% of the time. Please let me know if there is any workaround to help detect checkbox's referenced using label via watir? If there are none, I will wait for the fix. Thanks again.
