### ISSUE TITLE
text_field elements with type='email' can not be found with watir-classic in IE10 or IE11

### ISSUE THREAD

**Issue by tcfodor** [watir/watir-classic#68]
I'm using watir-classic 4.1.0 and IE11, but the issue happens with IE10 as well.  

The HTML5 email element is a text_field with format checking to make sure the text entered is a valid email address format.  watir-classic can't find these elements in IE10 or IE11, but can in IE9.

Here's an example: 

http://redstamp.ca/

The email field for signing up for the newsletter has the following HTML:

      <input name="EMAIL" class="required email" id="mce-EMAIL" type="email" placeholder="EMAIL ADDRESS" value=""/>

From my irb session:

    b = Watir::Browser.find(:url, /redstamp/)

    b.text_field(:name => 'EMAIL').exists?
    => false

(this returns true in IE9)

**Comment by jkotests** [comment]
This will be fixed in the next release.
