### ISSUE TITLE
"LoadError: cannot load such file -- dl/import" when using Ruby 2.2

### ISSUE THREAD

**Issue by jkotests** [watir/watir-classic#73]
When using Ruby 2.2, requiring Watir-Classic results in an exception. From what I gather, the problem is due to DL having been removed from Ruby.

````````
C:\Users\admin>irb
irb(main):001:0> require 'watir-classic'
LoadError: cannot load such file -- dl/import
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-classic-4.0.1/lib/watir-classic/win32.rb:1:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-classic-4.0.1/lib/watir-classic.rb:32:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in`require'
        from (irb):1
        from C:/Ruby22/bin/irb:11:in `<main>'
````````

It looks like this might only impact those who use the `modal_dialog` method.

**Comment by p0deje** [comment]
It has been [removed](https://github.com/ruby/ruby/blob/v2_2_0/NEWS#L148-L149).

I guess we should migrate code from DL to Fiddle. I'll try to do that as soon as possible.

**Comment by p0deje** [comment]
@jkotests I'm actually not around any Windows machine right now, so I can't test the fix.

Can you try the following patch?

```diff
diff --git a/lib/watir-classic/win32.rb b/lib/watir-classic/win32.rb
index 3fe27a4..349a9f9 100644
--- a/lib/watir-classic/win32.rb
+++ b/lib/watir-classic/win32.rb
@@ -1,5 +1,9 @@
-require 'dl/import'
-require 'dl/struct'
+if RUBY_VERSION =~ /^2\.2/
+  require 'fiddle/import'
+else
+  require 'dl/import'
+  require 'dl/struct'
+end
 require 'Win32API'
 
 module Watir
@@ -8,8 +12,14 @@ module Watir
     # this will find the IEDialog.dll file in its build location
     @@iedialog_file = (File.expand_path(File.dirname(__FILE__) + '/..') + "/watir-classic/IEDialog/Release/IEDialog.dll").gsub('/', '\\')
 
-    GetUnknown = Win32API.new(@@iedialog_file, 'GetUnknown', ['l', 'p'], 'v')    
-    User32 = DL.dlopen('user32')
+    GetUnknown = Win32API.new(@@iedialog_file, 'GetUnknown', ['l', 'p'], 'v')
+
+    if RUBY_VERSION =~ /^2\.2/
+      User32 = Fiddle.dlopen('user32')
+    else
+      User32 = DL.dlopen('user32')
+    end
+
     if RUBY_VERSION =~ /^1\.8/
       FindWindowEx = User32['FindWindowEx', 'LLLpp']
       # method for this found in wet-winobj/wet/winobjects/WinUtils.rb
```

**Comment by jkotests** [comment]
Sorry, I am away for a week. I can give it a try when I am back.

**Comment by jkotests** [comment]
@p0deje, unfortunately I cannot test your fix since it then errors out on the line:

````````
GetUnknown = Win32API.new(@@iedialog_file, 'GetUnknown', ['l', 'p'], 'v')
````````

With the error:

````````
"C:\\Ruby22\\lib\\ruby\\gems\\2.2.0\\gems\\watir-classic-4.0.1\\lib\\watir-classic\\IEDialog\\Release\\IEDialog.dll"
TypeError: no implicit conversion from nil to integer
  from C:/Ruby22/lib/ruby/2.2.0/Win32API.rb:16:in `initialize'
  from C:/Ruby22/lib/ruby/2.2.0/Win32API.rb:16:in `new'
  from C:/Ruby22/lib/ruby/2.2.0/Win32API.rb:16:in `initialize'
  from C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-classic-4.0.1/lib/watir-classic/win32.rb:15:in `new'
  from C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-classic-4.0.1/lib/watir-classic/win32.rb:15:in `<module:Win32>'
  from C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-classic-4.0.1/lib/watir-classic/win32.rb:11:in `<module:Watir>'
  from C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-classic-4.0.1/lib/watir-classic/win32.rb:9:in `<top (required)>'
  from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  from C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-classic-4.0.1/lib/watir-classic.rb:32:in `<top (required)>'
  from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
  from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
  from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in`require'
  from (irb):1
  from C:/Ruby22/bin/irb:11:in `<main>'
````````

Any chance you have any experience with the Win32API?

**Comment by p0deje** [comment]
@jkotests I don't. Guess I need to find Windows VM to properly fix this.

**Comment by jkotests** [comment]
@p0deje, if you need a Windows VM, you can get one from [modern.ie](http://dev.modern.ie/tools/vms/). They are free and available for Windows/Mac/Linux using VirtualBox. A trial version of Windows is used, so it expires after a month, at which point you just re-create the VM. However, since you only need to install Ruby and Watir, it is not the biggest hassle for the occasional use.

**Comment by predatorian3** [comment]
This was what worked for me until the code moves over. 

http://stackoverflow.com/a/28900142/2009612

**Comment by zhangxu01** [comment]
I have the similar issue. 
upgrade to ruby 2.2. When use "fiddle/import" to load My win32 DLL, it rescue the exception(Exec Format Error) for Fiddle.dlopen(lib). But dlload is fine on ruby 2.0
 
  Here is my code. 
  require "fiddle"
  require "fiddle/import"
  extend Fiddle::Importer
  dlload File.dirname(__FILE__) + '/my.dll'

**Comment by sohailchd** [comment]
Hey @p0deje 

Tried your fix on windows 7 with ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]
Got the following issues.

LoadError: Exec format error                                                                                               
        from C:/Ruby22-x64/lib/ruby/2.2.0/fiddle.rb:46:in `initialize'                                                     
        from C:/Ruby22-x64/lib/ruby/2.2.0/fiddle.rb:46:in `new'                                                            
        from C:/Ruby22-x64/lib/ruby/2.2.0/fiddle.rb:46:in `dlopen'                                                         
        from C:/Ruby22-x64/lib/ruby/2.2.0/Win32API.rb:14:in `initialize'                                                   
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/watir-classic-4.2.0/lib/watir-classic/win32.rb:15:in `new'             
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/watir-classic-4.2.0/lib/watir-classic/win32.rb:15:in `<module:Win32>'  
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/watir-classic-4.2.0/lib/watir-classic/win32.rb:11:in `<module:Watir>'  
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/watir-classic-4.2.0/lib/watir-classic/win32.rb:9:in `<top (required)>' 
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'                              
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'                              
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/watir-classic-4.2.0/lib/watir-classic.rb:32:in `<top (required)>'      
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'                             
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'                   
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'                              
        from (irb):1 in <main>

**Comment by ZigmaZigmax** [comment]
I am still getting this

C:/ruby23x64/lib/ruby/2.3.0/fiddle.rb:47:in `initialize': Exec format error (LoadError)
	from C:/ruby23x64/lib/ruby/2.3.0/fiddle.rb:47:in `new'
	from C:/ruby23x64/lib/ruby/2.3.0/fiddle.rb:47:in `dlopen'
	from C:/ruby23x64/lib/ruby/2.3.0/Win32API.rb:15:in `initialize'
	from C:/ruby23x64/lib/ruby/gems/2.3.0/gems/watir-classic-4.3.0/lib/watir-classic/win32.rb:15:in `new'
	from C:/ruby23x64/lib/ruby/gems/2.3.0/gems/watir-classic-4.3.0/lib/watir-classic/win32.rb:15:in `<module:Win32>'
	from C:/ruby23x64/lib/ruby/gems/2.3.0/gems/watir-classic-4.3.0/lib/watir-classic/win32.rb:11:in `<module:Watir>'
	from C:/ruby23x64/lib/ruby/gems/2.3.0/gems/watir-classic-4.3.0/lib/watir-classic/win32.rb:9:in `<top (required)>'
	from C:/ruby23x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/ruby23x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/ruby23x64/lib/ruby/gems/2.3.0/gems/watir-classic-4.3.0/lib/watir-classic.rb:32:in `<top (required)>'
	from C:/ruby23x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from C:/ruby23x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from C:/ruby23x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from C:/cygwin64/home/asdi/workspace/test1/test.rb:1:in `<main>'

**Comment by ughstudios** [comment]
Was this issue ever resolved? I am having this issue on windows

**Comment by jkotests** [comment]
@Bdoom, what version of Ruby are you using?

This bug was fixed in v4.3.0 specifically for Ruby 2.1/2.2. However, I have been using Ruby 2.3 and Watir-Classic v4.3.0 on Windows 7/10 without issue.

**Comment by ughstudios** [comment]
@jkotests 

We are using version 2.3.3p222 according to what I was told. This is for a rails project and whenever I run rake db:create I get the error saying dl/import does not work. And I check the callstack, it leads to the pageant.rb file for net-ssh

**Comment by jkotests** [comment]
@Bdoom, I upgraded to Ruby 2.3.3p222, but am still not able to reproduce the issue. If you can provide a minimal set of steps to reproduce, I can take a look.

However, you should note that Watir-Classic is deprecated and unlikely to get many fixes. Ideally, you should switch to using mainline Watir. On that note, it would be interesting to understand your reasons for still using Watir-Classic. I have been hoping I was the last one.
