### ISSUE TITLE
OT: Site watir.com not accessible

### ISSUE THREAD

**Issue by pdifeo** [watir/watir-classic#77]
The domain name is expired.

**Comment by p0deje** [comment]
@jkotests Can you take a look?

**Comment by pdifeo** [comment]
[image: Immagine in linea 1]

2015-06-24 6:27 GMT+02:00 Alex Rodionov <notifications@github.com>:

> @jkotests <https://github.com/jkotests> Can you take a look?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/watir/watir-classic/issues/77#issuecomment-114724205>.
>



-- 
Pasquale Di Feo
mailto:pdifeo@gmail.com

**Comment by jkotests** [comment]
@p0deje, I have contacted the Open Information Foundation.

**Comment by jkotests** [comment]
The domain has been renewed. Thanks for the reminder.
