### ISSUE TITLE
How to store a table instance?

### ISSUE THREAD

**Issue by liyucun** [watir/watir-classic#78]
Hi,

I have two tables on different page of my testing website, and I want to compare these two tables cell by cell, which contain span, button, image etc. So I assigned table A to one variable, and then click button navigate to next page which contain table B.

When I try to compare cell between these two tables, it raise error that table A is nil. The reason is because Watir look for table A on current browser page, which does not contain table A.

I am wondering if it is possible to assign such a table instance to one variable and use it in another page in Watir.

Thanks

**Comment by jkotests** [comment]
Unfortunately, Watir does not provide a method to save the table instance for use on another page.

You will need to extract the data of interest from the first table before going to second page/table.
