### ISSUE TITLE
watir-classic-4.2.0 conflicts with win32screenshot 2.1.0

### ISSUE THREAD

**Issue by kimiffx** [watir/watir-classic#80]
Hi

watir-classic not working with latest win32screenshot.

ruby 2.2.4 (2015-12-16 patchlevel 230) [i386-mingw32]
C:/Ruby224/lib/ruby/2.2.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate watir-classic-4.2.0, because win32screenshot-2.1.0 conflicts with win32screenshot (~> 2.0.0) (Gem::ConflictError)
	from C:/Ruby224/lib/ruby/2.2.0/rubygems/specification.rb:1280:in `activate'
	from C:/Ruby224/lib/ruby/2.2.0/rubygems/specification.rb:1314:in `block in activate_dependencies'
	from C:/Ruby224/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `each'
	from C:/Ruby224/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `activate_dependencies'
	from C:/Ruby224/lib/ruby/2.2.0/rubygems/specification.rb:1282:in `activate'
	from C:/Ruby224/lib/ruby/2.2.0/rubygems.rb:198:in `rescue in try_activate'
	from C:/Ruby224/lib/ruby/2.2.0/rubygems.rb:195:in `try_activate'
	from C:/Ruby224/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from C:/Ruby224/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from C:/Ruby224/lib/ruby/gems/2.2.0/gems/commonwatir-4.0.0/lib/watir.rb:1:in `<top (required)>'
	from C:/Ruby224/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from C:/Ruby224/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from C:/Ruby224/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from C:/workspace_ruby_mars/MedinetWatirTests/lib/Medinet_defs_main.rb:115:in `<top (required)>'
	from C:/Ruby224/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from C:/Ruby224/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from C:/workspace_ruby_mars/MedinetWatirTests/testing_minitest_reports.rb:11:in `<main>'

**Comment by jkotests** [comment]
Thanks. I will bump the version for win32screenshot when I publish the changes for working with later versions of Ruby (hopefully some time this week).

**Comment by jkotests** [comment]
The win32screenshot version has been bumped in the latest release.
